# Generated by Django 4.1.5 on 2023-02-01 11:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Создано, подготовлено к публикации'), (2, 'Опубликовано'), (3, 'В архиве')], default=1, verbose_name='Статус резюме')),
                ('grade', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='intern', max_length=6, verbose_name='Уровень')),
                ('specialty', models.CharField(choices=[('frontend', 'Фронтенд'), ('backend', 'Бэкенд'), ('gamedev', 'Геймдев'), ('devops', 'Девопс'), ('design', 'Дизайн'), ('products', 'Продукты'), ('management', 'Менеджмент'), ('testing', 'Тестирование')], default='backend', max_length=10, verbose_name='Специализация')),
                ('education', models.CharField(choices=[('secondary', 'Среднее общее'), ('secondary_special', 'Среднее специальное'), ('incomplete_higher', 'Неоконченное высшее'), ('higher', 'Высшее')], default='secondary', max_length=18, verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('portfolio', models.URLField(verbose_name='Ссылка на портфолио (GitHub или иные ресурсы)')),
                ('title', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер для связи')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для связи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
